
//SFML
#include<SFML/Graphics.hpp>
#include<SFML/Audio.hpp>
#include<SFML/Window.hpp>
#include<SFML/System.hpp>
//Core
#include<memory>
#include<algorithm>
#include<stack>
#include<map>
#include<unordered_map>
#include<set>
#include<vector>
#include<queue>
#include<string>
#include<iostream>
#include<sstream>
#include<fstream>
#include<cmath>
#include<thread>
#include<random>
#include<cstdlib>
